lr: 0.005
bpf: /home/jongsoo/beat-tracking/band_data
fps: 50
case: null
data:
  name: harmonix
  demixed: false
  num_instruments: 4
  num_labels: 10
  path_base_dir: /home/jongsoo/BeatTrackingDataset/harmonix/
  path_track_dir: /home/jongsoo/BeatTrackingDataset/harmonix/tracks/
  path_demix_dir: /home/jongsoo/BeatTrackingDataset/harmonix/demix/
  path_feature_dir: /home/jongsoo/BeatTrackingDataset/harmonix/features/
  path_no_demixed_feature_dir: /home/jongsoo/BeatTrackingDataset/harmonix/features_no_demixed/
  duration_min: 76
  duration_max: 660
  demucs_model: htdemucs
  bpfed: false
  path_bpf_dir: /home/jongsoo/BeatTrackingDataset/harmonix/bpf/
  path_bpf_feature_dir: /home/jongsoo/BeatTrackingDataset/harmonix/features_bpf/
  path_metadata: /home/jongsoo/BeatTrackingDataset/harmonix/metadata.csv
fmax: 11025
fmin: 30
fold: 0
seed: 1234
debug: false
depth: 6
model: allinonetemposum
sched: plateau
aafold: null
causal: false
epochs: 10
min_lr: 1.0e-07
swa_lr: 0.15
bpm_max: 240
bpm_min: 55
offline: false
act_conv: elu
hop_size: 441
qkv_bias: true
dice_loss: false
dim_embed: 24
dim_input: 81
drop_conv: 0.2
drop_last: 0
drop_path: 0.1
latency_t: 0
lookahead: false
mlp_ratio: 4
num_bands: 12
num_heads: 2
optimizer: radam
warmup_lr: 1.0e-05
batch_size: 512
decay_rate: 0.3
focal_loss: false
max_epochs: 6
drop_hidden: 0.2
eval_metric: val/loss
kernel_size: 5
learn_label: true
sample_rate: 22050
total_folds: 8
window_size: 2048
demucs_model: htdemucs
dilation_max: 3200
learn_rhythm: true
sanity_check: false
segment_size: 5
weight_decay: 0.00025
buffer_length: 5
gradient_clip: 0.5
learn_segment: true
warmup_epochs: 0
drop_attention: 0.2
layer_norm_eps: 1.0e-05
threshold_beat: 0.19
act_transformer: gelu
cooldown_epochs: 0
dilation_factor: 2
learn_structure: true
loss_weight_mag: 1
patience_epochs: 5
double_attention: true
loss_weight_beat: 1
loss_weight_focal: 3
loss_weight_tempo: 1
min_hops_per_beat: 24
sanity_check_size: 1
threshold_minimal: 0.5
threshold_section: 0.05
threshold_downbeat: 0.19
best_threshold_beat: null
instrument_attention: true
loss_weight_downbeat: 3
loss_weight_dice_beat: 0.1
best_threshold_downbeat: null
early_stopping_patience: 2
loss_weight_dice_downbeat: 0.3
validation_interval_epochs: 1
